const majorArcana = [
  { name: "The Fool", imgSrc: "images/majorArcana/0_theFool.jpg", },
  { name: "The Magician", imgSrc: "images/majorArcana/1_theMagician.jpg", },
  { name: "The High Priestess", imgSrc: "images/majorArcana/2_theHighPriestess.jpg", },
  { name: "The Empress", imgSrc: "images/majorArcana/3_theEmpress.jpg", },
  { name: "The Emperor", imgSrc: "images/majorArcana/4_theEmperor.jpg", },
  { name: "The Hierophant", imgSrc: "images/majorArcana/5_theHierophant.jpg", },
  { name: "The Lovers", imgSrc: "images/majorArcana/6_theLovers.jpg", },
  { name: "The Chariot", imgSrc: "images/majorArcana/7_theChariot.jpg", },
  { name: "Strength", imgSrc: "images/majorArcana/8_Strength.jpg", },
  { name: "The Hermit", imgSrc: "images/majorArcana/9_theHermit.jpg", },
  { name: "Wheel of Fortune", imgSrc: "images/majorArcana/10_wheelOfFortune.jpg", },
  { name: "Justice", imgSrc: "images/majorArcana/11_Justice.jpg", },
  { name: "The Hanged Man", imgSrc: "images/majorArcana/12_theHangedMan.jpg", },
  { name: "Death", imgSrc: "images/majorArcana/13_Death.jpg", },
  { name: "Temperance", imgSrc: "images/majorArcana/14_Temperance.jpg", },
  { name: "The Devil", imgSrc: "images/majorArcana/15_theDevil.jpg", },
  { name: "The Tower", imgSrc: "images/majorArcana/16_theTower.jpg", },
  { name: "The Star", imgSrc: "images/majorArcana/17_theStar.jpg", },
  { name: "The Moon", imgSrc: "images/majorArcana/18_theMoon.jpg", },
  { name: "The Sun", imgSrc: "images/majorArcana/19_theSun.jpg", },
  { name: "Judgment", imgSrc: "images/majorArcana/20_Judgment.jpg", },
  { name: "The World", imgSrc: "images/majorArcana/21_theWorld.jpg", },
];
